### ISSUE TITLE
Issues in letsencrypt role

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/roles#28]
I noticed that there's a couple of issues in the `letsencrypt` role:

```
- name: Generate certificates using webroot
  command: >
    {{ letsencrypt_command }} certonly {{ letsencrypt_flags }} --agree-tos -m "{{ letsencrypt_email }}"
    --webroot -w "{{ letsencrypt_webroot }}" -d {{ item.domains | join(' -d ') }}
  args:
    creates: /etc/letsencrypt/live/{{ item.domains[0] }}/fullchain.pem
  with_items: "{{ letsencrypt_certs }}"
  become: True
  become_user: "{{ letsencrypt_webuser }}"
  run_once: true
  when: letsencrypt_run|bool == true
  tags: ['letsencrypt', 'letsencrypt:run']
```

## The Issues
 - [x] ~There's a mysterious undocumented `-w` argument~ (false alarm)
 - [x]  `creates: ...fullchain.pem` should make Ansible skip the file as long as the certificate file exists, which is not the desired behavior in the case below :point_down: (fixed in #36)
 - [x] We always install the latest certbot, we should pin the version (fixed in #36)
 - [x] We need to support the new `certbot-auto renew` when the certificate exists (fixed in #36)
  - [x] I dislike the `server_name _;` on the `letsencrypt` role (~I've tried to fix it in #23~) a fix for it but it wasn't merged, mainly because I wasn't sure how this plays with the `custom_domain_*` variables (fixed in #24)
- [ ] We need to support the new `certbot-auto renew` in cronjob

### Issues with `creates`
When the certificate is about to end, there's no way to renew it with the Ansible `letsencyrpt` playbook. Because of `creates`, Ansible thinks that there's no more work to be done, thus falsly reporting that everything is `ok:`, which implies (to us mortals) that it ran the command while it didn't run the command since it saw the file `fullchain.pem` created.

**Comment by OmarIthawi** [comment]
@amirtds @thraxil @tkeemon @bryanlandia This are three reasons why we're having so much issues around `letsencrypt` certificates.

**Comment by OmarIthawi** [comment]
@natea We've already fixed most of the issues with our LetsEncrypt certbot. We have only one more issue to tackle (`cronjob`) all of the enterprise customers.
